language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
script: autoreconf -vfi && ./configure && make
before_install:
- sudo apt-get install build-essential autoconf automake libboost-dev libwtdbosqlite-dev libwthttp-dev libwtdbo-dev libwt-dev libconfig++-dev libzip-dev
