language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
before_install:
- sudo apt-get install build-essential autoconf automake cmake libboost-all-dev libconfig++-dev
- wget https://nih.at/libzip/libzip-1.0.1.tar.gz
- tar xvfp libzip-1.0.1.tar.gz
- pushd libzip-1.0.1 && ./configure --prefix=/usr && make && sudo make install
- popd
- git clone https://github.com/emweb/wt.git wt
- pushd wt;
- git checkout 3.3.4
- cmake -DWT_CPP_11_MODE=-std=c++11 -DCMAKE_INSTALL_PREFIX=/usr && sudo make install
- popd
script: autoreconf -vfi && ./configure && make
env:
  global:
    - MAKEFLAGS="-j 2"
