language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
before_install:
- sudo apt-get install build-essential autoconf automake cmake libboost-all-dev libconfig++-dev libzip-dev
- git clone https://github.com/emweb/wt.git wt
- pushd wt; git checkout 3.3.7; mkdir build; cd build
- cmake ../ -DWT_CPP_11_MODE=-std=c++11 -DCMAKE_INSTALL_PREFIX=/usr
- sudo make install
- popd
script: autoreconf -vfi && ./configure && make

