arch:
- amd64
- arm64
language: cpp
os: linux
dist: focal
addons:
    apt:
        packages:
        - build-essential
        - cmake
        - libboost-all-dev
        - libconfig++-dev
compiler:
- clang
- gcc
before_install:
- |
    if [ ! -d ${HOME}/wt-${WT_VERSION}/include ]; then
        git clone https://github.com/emweb/wt.git wt
        cd wt
        git checkout ${WT_VERSION}
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${WT_INSTALL_PREFIX} -DBUILD_EXAMPLES=OFF -DENABLE_LIBWTTEST=OFF -DCONNECTOR_FCGI=OFF
        make install
        cd ..
    fi
script: mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=${WT_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && make && make test
cache:
    directories:
    - ${HOME}/wt-${WT_VERSION}
env:
    global:
    - MAKEFLAGS="-j 2"
    - WT_VERSION=4.5.0
    - WT_INSTALL_PREFIX=${HOME}/wt-${WT_VERSION}
    jobs:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

# clang7 is not enough for full c++17 support
jobs:
    exclude:
    - compiler: clang
      arch: amd64
