name: Build
on: [push]
env:
    WT_VERSION=4.5.0
    WT_INSTALL_PREFIX=${GITHUB_WORKSPACE}-${WT_VERSION}
    BUILD_TYPE=Release
jobs:
    Build:
        runs-on: ubuntu-latest
        - uses:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo apt-get install --no-install-recommends build-essential cmake libboost-all-dev libconfig++-dev
            - name: Install Wt
              uses: actions/checkout@v2
              with:
                  repository: emweb/wt
                  ref: 4.5.0
                  path: wt
            - name: Build Wt
              run: cd wt && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=${WT_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && make && make test

