name: Build
on: [push]
env:
    BUILD_TYPE: Release
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo apt-get install --no-install-recommends build-essential cmake libboost-all-dev libconfig++-dev
            - name: Install Wt dependency
              uses: myci-actions/add-deb-repo@10
              with:
                  repo: deb https://debian.poupon.io/apt/debian buster main
                  repo-name: epoupon
                  key-asc: https://debian.poupon.io/apt/debian/epoupon.gpg.key
              run: sudo apt-get install --no-install-recommends libwt4-dev

