name: Build
on: [push, pull_request]
jobs:
  Build:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
    runs-on: ubuntu-latest
    steps:
      - name: Custom wt repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb https://debian.poupon.io/apt/debian buster main
          repo-name: epoupon
          keys-asc: https://debian.poupon.io/apt/debian/epoupon.gpg.key
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends build-essential cmake libboost-all-dev libconfig++-dev libwt4-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} && make && make test

  Docker:
    name: Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileshelter:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

