name: Build
on: [push]
jobs:
    Build:
        strategy:
            matrix:
                BUILD_TYPE: [Release, Debug]
        runs-on: ubuntu-latest
        steps:
            - name: Custom wt repository
              uses: myci-actions/add-deb-repo@10
              with:
                  repo: deb https://debian.poupon.io/apt/debian buster main
                  repo-name: epoupon
                  keys-asc: https://debian.poupon.io/apt/debian/epoupon.gpg.key
            - name: Install dependencies
              run: sudo apt-get install --no-install-recommends build-essential cmake libboost-all-dev libconfig++-dev libwt4-dev
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build
              run: mkdir build && cd build && cmake .. -DCMAKE_RELEASE_TYPE=${{ matrix.BUILD_TYPE }} && make && make test
